import { resolveMx } from 'node:dns/promises'
import { z } from 'zod'

const bodySchema = z.object({
  email: z.string().max(320),
})

// ── format ────────────────────────────────────────────────────────────────────

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/

function isValidFormat(email: string): boolean {
  return EMAIL_RE.test(email) && z.string().email().safeParse(email).success
}

// ── disposable domain block list ──────────────────────────────────────────────

const DISPOSABLE_DOMAINS = new Set([
  '10minutemail.com',
  '10minutemail.net',
  '20minutemail.com',
  'airmail.in',
  'anonymail.dk',
  'antichef.com',
  'antichef.net',
  'beefmilk.com',
  'binkmail.com',
  'bobmail.info',
  'bofthew.com',
  'bsnow.net',
  'bugmenot.com',
  'bumpymail.com',
  'casualdx.com',
  'chogmail.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'curryworld.de',
  'dacoolest.com',
  'dingbone.com',
  'discard.email',
  'discardmail.com',
  'dispostable.com',
  'dm.w3internet.co.uk',
  'dodgit.com',
  'dontreg.com',
  'dontsendmespam.de',
  'e4ward.com',
  'emailisvalid.com',
  'emailsensei.com',
  'emailwarden.com',
  'evilzone.org',
  'explodemail.com',
  'fakeinbox.com',
  'fakemail.fr',
  'filzmail.com',
  'fmailbox.com',
  'fmailc.com',
  'frapmail.com',
  'front14.org',
  'fugitiveemail.com',
  'getairmail.com',
  'getonemail.net',
  'ghosttexter.de',
  'gishpuppy.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'h8s.org',
  'haltospam.com',
  'hatespam.org',
  'herp.in',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'hopemail.biz',
  'hulapla.de',
  'ieatspam.eu',
  'ieatspam.info',
  'imails.info',
  'inboxclean.com',
  'inboxclean.org',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'ipoo.org',
  'Irish2me.com',
  'it2mail.com',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'junk1.tk',
  'klassmaster.com',
  'klassmaster.net',
  'klzlk.com',
  'kurzepost.de',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lortemail.dk',
  'lr78.com',
  'maildrop.cc',
  'mailexpire.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailimate.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailme.lv',
  'mailnew.com',
  'mailnull.com',
  'mailnesia.com',
  'mailscrap.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailzilla.com',
  'makemetheking.com',
  'manybrain.com',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'mintemail.com',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mt2009.com',
  'mt2014.com',
  'mytrashmail.com',
  'netzidiot.de',
  'neverbox.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nospam4.us',
  'nospamfor.us',
  'nospamthanks.info',
  'notmailinator.com',
  'notsharingmy.info',
  'nowmymail.com',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odaymail.com',
  'oneoffemail.com',
  'onewaymail.com',
  'online.ms',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pimpedupmyspace.com',
  'pojok.ml',
  'politikerclub.de',
  'poomail.com',
  'postacı.tk',
  'privacy.net',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'recode.me',
  'recursor.net',
  'regbypass.comsafe-mail.net',
  'rhyta.com',
  's0ny.net',
  'safe-mail.net',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharklasers.com',
  'shiftmail.com',
  'shitmail.me',
  'shitware.nl',
  'shortmail.net',
  'sibmail.com',
  'sneakemail.com',
  'sofimail.com',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam4.me',
  'spamavert.com',
  'spamcon.org',
  'spamfree24.org',
  'spamgoes.in',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamthisplease.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tagyourself.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempalias.com',
  'tempe-mail.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.it',
  'tempmail2.com',
  'tempomail.fr',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'thanksnospam.info',
  'thisisnotmyrealemail.com',
  'throam.com',
  'throwam.com',
  'throwaway.email',
  'throwam.com',
  'throwjunk.com',
  'tilien.com',
  'tmail.com',
  'tmailinator.com',
  'toiea.com',
  'topranklist.de',
  'trashdevil.com',
  'trashemail.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.io',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmailer.com',
  'trashymail.com',
  'trbvm.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'uroid.com',
  'valemail.net',
  'vidchart.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'xyzfree.net',
  'yahomail.tk',
  'yeah.net',
  'yep.it',
  'yomail.info',
  'yopmail.com',
  'yopmail.fr',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zebins.com',
  'zebins.eu',
  'zepp.dk',
  'zippymail.info',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
])

function isDisposable(domain: string): boolean {
  return DISPOSABLE_DOMAINS.has(domain.toLowerCase())
}

// ── MX lookup ─────────────────────────────────────────────────────────────────

async function hasMxRecord(domain: string): Promise<boolean> {
  try {
    const records = await resolveMx(domain)
    return records.length > 0
  } catch {
    return false
  }
}

// ── handler ───────────────────────────────────────────────────────────────────

export async function POST(request: Request) {
  try {
    const body = bodySchema.parse(await request.json())
    const email = body.email.trim()

    // 1. Format check
    if (!email || !isValidFormat(email)) {
      return Response.json({ valid: false, reason: 'Enter a valid email address.' })
    }

    const domain = email.split('@')[1].toLowerCase()

    // 2. Disposable block
    if (isDisposable(domain)) {
      return Response.json({ valid: false, reason: 'Disposable email addresses are not accepted.' })
    }

    // 3. MX record lookup
    const mx = await hasMxRecord(domain)
    if (!mx) {
      return Response.json({ valid: false, reason: "That email domain doesn't appear to accept mail." })
    }

    return Response.json({ valid: true })
  } catch (error) {
    if (error instanceof z.ZodError) {
      return Response.json({ valid: false, reason: 'Enter a valid email address.' })
    }
    console.error('check-email failed', error)
    // On unexpected errors, allow the email through to avoid blocking real submissions
    return Response.json({ valid: true })
  }
}
